plugins {
    id 'java'
    id 'application'
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/task_2']
        }
    }
}

group = 'com.example'
version = '1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'Main'
}

run {
    standardInput = System.in
}
